// packages/angular-a11y-date-input/src/date-input/date-input.component.ts
import { Component, ElementRef, EventEmitter, Input, OnDestroy, OnInit, Output, ViewChild, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';

@Component({
    selector: 'lib-date-input',
    standalone: true,
    schemas: [CUSTOM_ELEMENTS_SCHEMA],
    templateUrl: './date-input.component.html',
})
export class DateInputComponent implements OnInit, OnDestroy {
    @ViewChild('DateInput', { static: true })
    DateInput!: ElementRef<HTMLElement>;

    @Input() value?: Date;
    @Input() placeholder?: string;
    @Input() minYear?: number = 1900;
    @Input() maxYear?: number = 2100;
    @Input() defaultYear?: number;
    @Input() locale?: string = 'en-US';
    @Input() showTime?: boolean = false;

    @Output() dateChange = new EventEmitter<Date | null>();

    private listener?: (event: Event) => void;

    ngOnInit() {
        this.listener = (event: Event) => {
            const customEvent = event as CustomEvent<{ date: Date | null }>;
            this.dateChange.emit(customEvent.detail.date);
        };

        this.DateInput.nativeElement.addEventListener('date-change', this.listener);
    }

    ngOnDestroy() {
        if (this.listener) {
            this.DateInput.nativeElement.removeEventListener('date-change', this.listener);
        }
    }
}

<date-input
    #DateInput
    [attr.value]="value"
    [attr.placeholder]="placeholder"
    [attr.min-year]="minYear"
    [attr.max-year]="maxYear"
    [attr.default-year]="defaultYear"
    [attr.locale]="locale"
    [attr.show-time]="showTime"
></date-input>

// packages/svelte-a11y-date-input/src/DateInput.svelte
<script lang="ts">
  import '@repo/a11y-date-input';
  import { onMount } from 'svelte';

  export let value: Date | undefined = undefined;
  export let placeholder: string | undefined = undefined;
  export let minYear: number | undefined = 1900;
  export let maxYear: number | undefined = 2100;
  export let defaultYear: number | undefined = undefined;
  export let locale: string | undefined = 'en-US';
  export let showTime: boolean = false;
  export let onDateChange: ((date: Date | null) => void) | undefined = undefined;

  let element: HTMLElement;

  onMount(() => {
    const handleDateChange = (e: Event) => {
      const customEvent = e as CustomEvent<{ date: Date | null }>;
      onDateChange?.(customEvent.detail.date);
    };

    element.addEventListener('date-change', handleDateChange);

    return () => {
      element.removeEventListener('date-change', handleDateChange);
    };
  });

  // Update value when it changes externally
  $: if (element && value !== undefined) {
    (element as any).value = value;
  }
</script>

<date-input
  bind:this={element}
  {value}
  {placeholder}
  min-year={minYear}
  max-year={maxYear}
  default-year={defaultYear}
  {locale}
  show-time={showTime}
/>
