// packages/svelte-a11y-date-input/src/DateRangeInput.svelte
<script lang="ts">
  import '@repo/a11y-date-input';
  import { onMount } from 'svelte';

  export let startDate: Date | undefined = undefined;
  export let endDate: Date | undefined = undefined;
  export let minYear: number | undefined = 1900;
  export let maxYear: number | undefined = 2100;
  export let defaultYear: number | undefined = undefined;
  export let locale: string | undefined = 'en-US';
  export let onRangeChange:
    | ((startDate: Date | null, endDate: Date | null) => void)
    | undefined = undefined;

  let element: HTMLElement;

  onMount(() => {
    const handleRangeChange = (e: Event) => {
      const customEvent = e as CustomEvent<{
        startDate: Date | null;
        endDate: Date | null;
      }>;
      onRangeChange?.(customEvent.detail.startDate, customEvent.detail.endDate);
    };

    element.addEventListener('range-change', handleRangeChange);

    return () => {
      element.removeEventListener('range-change', handleRangeChange);
    };
  });

  // Update values when they change externally
  $: if (element) {
    if (startDate !== undefined) {
      (element as any).startDate = startDate;
    }
    if (endDate !== undefined) {
      (element as any).endDate = endDate;
    }
  }
</script>

<date-range-input
  bind:this={element}
  start-date={startDate}
  end-date={endDate}
  min-year={minYear}
  max-year={maxYear}
  default-year={defaultYear}
  {locale}
/>

// packages/angular-a11y-date-input/src/date-range-input/date-range-input.component.ts
import { Component, ElementRef, EventEmitter, Input, OnDestroy, OnInit, Output, ViewChild, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';

export interface DateRange {
    startDate: Date | null;
    endDate: Date | null;
}

@Component({
    selector: 'lib-date-range-input',
    standalone: true,
    schemas: [CUSTOM_ELEMENTS_SCHEMA],
    template: `
        <date-range-input
            #dateRangeInput
            [attr.start-date]="startDate"
            [attr.end-date]="endDate"
            [attr.min-year]="minYear"
            [attr.max-year]="maxYear"
            [attr.default-year]="defaultYear"
            [attr.locale]="locale"
        ></date-range-input>
    `,
})
export class DateRangeInputComponent implements OnInit, OnDestroy {
    @ViewChild('dateRangeInput', { static: true })
    dateRangeInput!: ElementRef<HTMLElement>;

    @Input() startDate?: Date;
    @Input() endDate?: Date;
    @Input() minYear?: number = 1900;
    @Input() maxYear?: number = 2100;
    @Input() defaultYear?: number;
    @Input() locale?: string = 'en-US';

    @Output() rangeChange = new EventEmitter<DateRange>();

    private listener?: (event: Event) => void;

    ngOnInit() {
        this.listener = (event: Event) => {
            const customEvent = event as CustomEvent<{
                startDate: Date | null;
                endDate: Date | null;
            }>;
            this.rangeChange.emit({
                startDate: customEvent.detail.startDate,
                endDate: customEvent.detail.endDate,
            });
        };

        this.dateRangeInput.nativeElement.addEventListener('range-change', this.listener);
    }

    ngOnDestroy() {
        if (this.listener) {
            this.dateRangeInput.nativeElement.removeEventListener('range-change', this.listener);
        }
    }
}
